APP_NAME=Netacube
APP_ENV=production
APP_KEY=base64:pPhX1HYyTA5bW6cEUly67zsk0xDhvBa/PhulAVNAB2Q=
APP_DEBUG=false
APP_URL=https://netacube.net

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=premiate_netacubemaster
DB_USERNAME=premiate_netacubemaster
DB_PASSWORD=binto2020

TENANT_DB_PASSWORD=binto2020

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local000
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=480

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=netacube1@gmail.com
MAIL_PASSWORD=mjhqctlhalgzlzkp
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=netacube1@gmail.com
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_HOST=
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=mt1

VITE_APP_NAME="${APP_NAME}"
VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="${PUSHER_HOST}"
VITE_PUSHER_PORT="${PUSHER_PORT}"
VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

CPANEL_DOMAIN=netacube.net
CPANEL_USERNAME=premiate
CPANEL_API_TOKEN=YMYFR68OEZS1570IOYD1N7ULTYRQ9T9P
CPANEL_PORT=2083